### ISSUE TITLE
Getting Error when navigating to dashboard

### ISSUE THREAD

**Issue by isaackearl** [phpsa/statamic-analytics#2]
I'm on the latest version (1.2.0).  This is my first time purchasing this plugin, but I plan on using it more in the future for clients that want that.

I get the following error when I click on dashboard:

Call to a member function pluck() on null (View: ../vendor/phpsa/statamic-analytics/resources/views/widgets/top-referrers.blade.php) (line 83) 

![image](https://user-images.githubusercontent.com/9354830/108376158-adec1a80-71d0-11eb-875d-ac3835ee2e85.png)

**Comment by phpsa** [comment]
Looking into this now, - has this account got a lot of views / perhaps a new one without any views yet?

**Comment by phpsa** [comment]
I have managed to replicate by having the incorrect view id stored, i have added some error handling around that and it will now show a friendly message when this occurs - release 1.2.1

**Comment by isaackearl** [comment]
The page has been around for a while, but it doesn't get a ton of views.  It is for a small local business.  Here is a screenshot from the actual analytics page at analytics.google.com 

![image](https://user-images.githubusercontent.com/9354830/108554919-c5a3cb80-72c2-11eb-9b71-1de062421371.png)

**Comment by phpsa** [comment]
Please let me know if 1.2.1 release sorts your issue out.

**Comment by phpsa** [comment]
Considering this solved as no response since update

**Comment by isaackearl** [comment]
@phpsa Yes it is working now!  Thanks again and sorry for the late response.  Been a bit busy and forgot to respond to your last message.
